"""DevAgent — implements tasks via Claude Code in isolated git worktrees."""
import logging
import uuid
from collections import namedtuple
from dataclasses import dataclass, field
from typing import Optional

from agents.base import BaseAgent
from tools.claude_code import ClaudeCodeTool
from tools.git_tool import GitTool
from memory.task_store import TaskStore

logger = logging.getLogger("nanoclaw.agents.dev")

PRInfo = namedtuple("PRInfo", ["url", "number"])


@dataclass
class DevResult:
    """Returned by DevAgent.implement(). Shape used by WorkflowEngine + QAAgent."""
    verification_passed: bool
    worktree_path: str
    branch: str
    details: str
    files_changed: list[str] = field(default_factory=list)
    error: Optional[str] = None
    # pr_url is NOT here — set by commit_and_push() after approval


class DevAgent(BaseAgent):
    name = "dev"
    task_type = "coding"
    prompt_file = "config/prompts/dev_prompt.md"

    def __init__(self, router, memory, context,
                 claude_code: ClaudeCodeTool,
                 git: GitTool,
                 task_store: TaskStore):
        super().__init__(router, memory, context)
        self.claude_code = claude_code
        self.git = git
        self.task_store = task_store

    async def implement(self, task: dict,
                        session_id: str = None) -> DevResult:
        """
        Full implementation cycle for one task:
        1. Create worktree
        2. Build Claude Code instruction from task spec
        3. Execute Claude Code in worktree
        4. VerificationLayer runs automatically inside ClaudeCodeTool
        5. Return DevResult (success/failure + worktree_path + branch)

        Does NOT commit or push — that happens in commit_and_push() after approval.
        """
        session_id = session_id or str(uuid.uuid4())

        # 1. Create worktree
        worktree_path = self.git.create_worktree(
            task["id"], task.get("title", ""),
        )
        branch = self.git.get_branch(worktree_path)

        # Update task with worktree info
        await self.task_store.update(
            task["id"],
            status="in_progress",
            worktree_path=worktree_path,
            branch=branch,
        )

        # 2. Build instruction
        instruction = self._build_instruction(task)

        # 3. Execute Claude Code (verification runs inside)
        result = await self.claude_code.run(
            instruction=instruction,
            worktree_path=worktree_path,
            task=task,
        )

        # 4. Collect changed files
        files_changed = self.git.get_changed_files(worktree_path)

        # 5. Save to memory
        await self.memory.save_message(
            role=self.name, agent=self.name,
            content=f"Implementation result for {task['id']}: "
                    f"{'success' if result.success else 'failed'}\n{result.output}",
            task_id=task["id"],
        )

        if not result.success:
            return DevResult(
                verification_passed=False,
                worktree_path=worktree_path,
                branch=branch,
                details=result.output,
                files_changed=files_changed,
                error=result.error,
            )

        return DevResult(
            verification_passed=True,
            worktree_path=worktree_path,
            branch=branch,
            details=result.output,
            files_changed=files_changed,
        )

    async def commit_and_push(self, task: dict,
                              dev_result: DevResult) -> "PRInfo":
        """
        Called ONLY after WorkflowEngine receives QA pass.
        Returns PRInfo(url, number).
        """
        # Commit
        message = f"feat({task['id']}): {task.get('title', 'implementation')}"
        self.git.commit(dev_result.worktree_path, message)

        # Push
        self.git.push(dev_result.worktree_path)

        # Create PR
        pr_title = f"[NanoClaw] {task['id']}: {task.get('title', '')}"
        pr_body = (
            f"## Task\n{task.get('description', '')}\n\n"
            f"## Acceptance Criteria\n"
            + "\n".join(f"- [ ] {ac}" for ac in task.get("acceptance_criteria", []))
            + f"\n\n## Files Changed\n"
            + "\n".join(f"- `{f}`" for f in dev_result.files_changed)
            + "\n\n---\n*Generated by NanoClaw DevAgent*"
        )
        pr_url = await self.git.create_pr(
            pr_title, pr_body, dev_result.branch,
        )

        # Extract PR number from URL (always ends in /<number>)
        pr_number = int(pr_url.rstrip("/").rsplit("/", 1)[-1])

        # Clean up worktree
        self.git.remove_worktree(dev_result.worktree_path)

        # Update task
        await self.task_store.update(
            task["id"], status="done", pr_url=pr_url,
        )

        return PRInfo(url=pr_url, number=pr_number)

    def _build_instruction(self, task: dict) -> str:
        """Build a Claude Code instruction from the task spec."""
        criteria = "\n".join(
            f"- {ac}" for ac in task.get("acceptance_criteria", [])
        )
        return (
            f"## Task: {task.get('title', '')}\n\n"
            f"{task.get('description', '')}\n\n"
            f"## Acceptance Criteria\n{criteria}\n\n"
            f"## Rules\n"
            f"- Write clean, production-quality code\n"
            f"- Add tests for new functionality\n"
            f"- Do not modify files outside the scope of this task\n"
        )
